### ISSUE TITLE
Arabic is separated and reversed !

### ISSUE THREAD

**Issue by msliman** [rossmc/SalesPdfFonts#1]

**Comment by rossmc** [comment]
@msliman, I'm sorry this module does not support arabic.  Although the [GNU font](https://www.gnu.org/software/freefont/) does say it supports Arabic, perhaps it's a bug with the GNU Font or something else with magento

You could try forking the project yourself and changing the font from GNU Free Font to another one which supports Arabic. There is probably a [Noto font](https://www.google.com/get/noto/) which supports Arabic.  

If memory serves me right, you will only need to upload the font files which you select to [view/adminhtml/web/fonts](https://github.com/rossmc/SalesPdfFonts/tree/master/view/adminhtml/web/fonts) and change the [Model/Order/Pdf/SetFontTrait.php](https://github.com/rossmc/SalesPdfFonts/blob/master/Model/Order/Pdf/SetFontTrait.php) file accordingly.

**Comment by msliman** [comment]
Thank you.. I tried Noto font (Noto Sans Arabic & Noto Kufi Arabic)  and updated the Model SetFontTrait.php and both of them gives error 

a:4:{i:0;s:30:"Unable to read version 4 table";i:1;s:5227:"#0 /var/www/html/magento217/vendor/magento/zendframework1/library/Zend/Pdf/Font.php(615): Zend_Pdf_Font::_extractTrueTypeFont(Object(Zend_Pdf_FileParserDataSource_File), 0)
#1 /var/www/html/magento217/app/code/Rossmc/SalesPdfFonts/Model/Order/Pdf/SetFontTrait.php(43): Zend_Pdf_Font::fontWithPath('/var/www/html/m...')

Kindly Can you help ?

**Comment by rossmc** [comment]
@msliman that error suggests that Magento cannot read the font you changed it to.

I created a new [noto-sans-arabic branch](https://github.com/rossmc/SalesPdfFonts/tree/noto-sans-arabic), which uses the noto-sans-arabic  font, try that one. Hopefully it works.

**Comment by msliman** [comment]
Hi thank you for your help. I tried the new branch but I got the same error 

a:4:{i:0;s:30:"Unable to read version 4 table";i:1;s:5227:"#0 /var/www/html/magento217/vendor/magento/zendframework1/library/Zend/Pdf/Font.php(615): Zend_Pdf_Font::_extractTrueTypeFont(Object(Zend_Pdf_FileParserDataSource_File), 0)
#1 /var/www/html/magento217/app/code/Rossmc/SalesPdfFonts/Model/Order/Pdf/SetFontTrait.php(39): Zend_Pdf_Font::fontWithPath('/var/www/html/m...')

**Comment by msliman** [comment]
@rossmc Waiting your reply, I am stuck in this problem for 3 days. 
Appreciate your help.

**Comment by rossmc** [comment]
@msliman I don't have time to work on this, I'm afraid it doesn't support Arabic.  Perhaps look for a different module.

**Comment by YazeedNashad** [comment]
Hi @msliman,
This problem I've had, so have you been able to find a solution?

**Comment by msliman** [comment]
Hi @YazeedNashad 

No I didn't find. this problem is related to ZendPDF.
